GROQ_API_KEY = "your-groq-api-key-here"
GROQ_TRANSCRIPTION_MODEL = "whisper-large-v3-turbo"
GROQ_TRANSLATION_MODEL = "llama-3.1-8b-instant"

# Optional tuning:
# RTDT_TRANSCRIPTION_MODE = "fast"
# RTDT_TRANSCRIPTION_LANGUAGE = "en"
# RTDT_TRANSCRIPTION_TEMPERATURE = "0"
# RTDT_TRANSCRIPTION_PROMPT = "This is an English motivational speech. Common words: power of words, adversity, opportunity, weakness, strength, disabled, differently abled, disability."
# RTDT_RECORD_TIMEOUT = "1.0"
# RTDT_PHRASE_TIMEOUT = "3.0"
# RTDT_PAUSE_THRESHOLD = "0.50"
# RTDT_MIN_AUDIO_SECONDS = "0.30"
# RTDT_MIN_AUDIO_RMS = "120"
# RTDT_MIN_MIC_RMS = "120"
# RTDT_MIN_SPEAKER_RMS = "90"
# RTDT_ENABLE_AUDIO_NORMALIZATION = "1"
# RTDT_TARGET_AUDIO_RMS = "800"
# RTDT_PRIORITIZE_SPEAKER = "1"
# RTDT_UI_REFRESH_MS = "150"
# RTDT_PROCESSING_STATUS_DELAY = "0.15"
